# Generated by Django 4.2.16 on 2024-12-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='answersheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('predicted_answer', models.CharField(max_length=1)),
                ('correct_answer', models.CharField(max_length=1)),
                ('confidence', models.FloatField()),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.answersheet')),
            ],
        ),
    ]
